
modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="GPLv3"
issueTrackerURL="https://github.com/nicobomber77/BlockDestroyer/issues"

[[mods]] #mandatory
modId="lumberstroyer" #mandatory
version="1.0" #mandatory
displayName="LumberStroyer" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="logo.png"
authors="nik77"
description='''
Want to be able to destroy trees faster? You are in the right place!
This mod adds a new enchantment "Bane Of Trees" that goes from 1 to 10, if you have this enchant on an axe trees will be magically destroyed.
The speed depends on the level of the enchant.
'''

